# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8790510caa698bb2930876a74c591740313b8208d85489fb8d24d9ac631963993a1b8857fce5742041747095c8f92d3701c07cf8ddcf5c17053316659b03519

test:
  secret_key_base: 01b07d304550569582d438f110f25d249cae12b6f69da0d8e7656b49dd61041434a4fdb97b92bea3e36f983acf8049958923b398381f7ea5267025da0811ce21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
